name: mellowminds
version: 1.0.0+1
publish_to: none
description: Mellow Minds.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_appauth: 6.0.6
  flutter_secure_storage: 9.2.2
  crypto: ^3.0.3
  dio: ^5.4.1
  flutter_image_compress: ^2.2.0
  get_storage: ^2.1.1
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  google_fonts: ^6.1.0
  substring_highlight: ^1.0.33
  flutter_screenutil: ^5.9.0
  gap: 3.0.1
  flutter: 
    sdk: flutter
  magic_view: 
    git: 
      url: https://github.com/ajianaz/MagicView.git
      ref: a9d82b7
  adk_tools: 
    git: 
      url: https://github.com/ajianaz/adk_tools.git
      ref: c9f522c

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

